### ISSUE TITLE
OutOfMemoryError for large response body

### ISSUE THREAD

**Issue by asarkar** [devcsrj/slf4j-okhttp3-logging-interceptor#3]
The fact that logging of the response body is deduced from the logging level `DEBUG` causes `OutOfMemoryError` for large response bodies, because the code tries to buffer the whole response in memory [HttpLoggingInterceptor.java#L257](https://github.com/devcsrj/slf4j-okhttp3-logging-interceptor/blob/master/src/main/java/devcsrj/okhttp3/logging/HttpLoggingInterceptor.java#L257).
```
BufferedSource source = responseBody.source();
source.request(Long.MAX_VALUE); // Buffer the entire body.
```
I realized that I can simply use the official [logging interceptor](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor) that doesn't have this problem as shown below.
```
HttpLoggingInterceptor logging = new HttpLoggingInterceptor(log::info)
    .setLevel(HEADERS);
```

Here, the message is logged at `INFO` level and the logging detail is chosen as `HEADERS`, which doesn't log the body. I could, just as easily, have chosen logging level `DEBUG` without any problem. In your implementation, that is not possible because you mixed up the two different logging levels.

Like I showed above, the official logging interceptor can be used to SLF4J without any problem, and I don't see much value in your fork anymore. However, I do strongly recommend documenting this so that no one else trips upon this issue like I did.

**Comment by devcsrj** [comment]
The goal of this library is to set slf4j (being it already the de-facto for java projects) as the facade for configuring the log levels of okhttp, i.e.: `DEBUG` for "header+body", and `INFO` for "header". While it's true that you can achieve it with the out-of-the-box logger by okhttp, I'm not a fan of going back to the code just to set the granularity of the content to dump (think production). 

I wrote this so that changing the log levels is as simple as, in log4j for example:

```
log4j.logger.okhttp3.logging.wire=INFO # log just the headers
```

> If you've used apache http client before, the wire dumping [configuration is similar](https://hc.apache.org/httpcomponents-client-ga/logging.html). Hence, the inspiration for this library.

FWIW, the snippet you pasted with regards the logger buffering the entire body is exactly the same as from the [official one](https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java#L239-L240).

Nevertheless, feel free to use whichever works best for you! :)

**Comment by asarkar** [comment]
Well, if the Apache HTTP Client runs out of memory by doing what you're doing, it's hardly a good reference. I've already moved to using to using the official logging interceptor, so it doesn't bother me, but your inability to understand the gravity of the issue and refusal to fix it will prevent the use of this interceptor in real world applications. I'll get my coat, thanks for your response and effort.

**Comment by devcsrj** [comment]
> ..to understand the gravity of the issue..

Tell that to the square/okhttp team too then! :) If you bothered clicking at the links on my previous comment, you should've seen that this interceptor is literally a mirror of [theirs](https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java#L239-L240) (except with slf4j, that is) - but no, you didn't. You entirely missed the point of referencing the apache httpclient - it was for the configuration approach, not implementation. 

> ..in real world applications.

Not to burst your bubble, but dumping of request-response body is turned off in **real-world production applications**. *cough*

>  ..refusal to fix it..

Looks like you haven't noticed yet, but it's **open-source**. Pull requests are free. I never said it'll never get fixed, I just don't appreciate people dissing around instead of taking actions.

> I'll get my coat..

Close the door behind you!

**Comment by asarkar** [comment]
> Not to burst your bubble

The only bubble that's showing is you copy-pasting the interceptor and gloating on it. A monkey can write an interceptor, it's not rocket science. You need a mirror in the house, not a computer.

> open-source

That's funny. Who'd want to take time to improve your copy-pasted junk? Christmas is over, stop flattering yourself.
